services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - USER_ID=${UID}
    volumes:
      - .:/home/rosuser/colcon_ws/src/arips_ros2
      - /dev:/dev
    group_add:
      - dialout
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    command: bash
