services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      target: robot
      args:
        USER_UID: 1000
    volumes:
      - ../../:/home/rosuser/colcon_ws
      - /dev:/dev
    group_add:
      - dialout
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    command: bash
