services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - USER_ID=${UID}
    volumes:
      - ../../:/home/rosuser/colcon_ws/
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/rosuser/.Xauthority
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}:ro
    group_add:
      - dialout
    devices:
      - /dev/dri:/dev/dri
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: /tmp/.Xauthority
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    command: bash
