components:
  base_power:
    package: arips_launch
    file: launch/base_power.launch.py
    dependencies: []  # no dependencies
  xbox_teleop:
    package: arips_launch
    file: launch/teleop_xbox.launch.py
    dependencies: [base_power]
